
import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"; // Correct path for global CSS
import Navbar from "../Components/Navbar";
import Footer from "../Components/Footer";

const geistSans = localFont({
  src: "/fonts/GeistVF.woff", // Correct path for fonts in the public folder
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff", // Correct path for fonts in the public folder
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        <main>{children}</main> {/* Ensure children is wrapped in main */}
        <Footer />
      </body>
    </html>
  );
}